name: Cron Runner

on:
  schedule:
    - cron: "*/113 * * * *" # Every 113 minutes
  workflow_dispatch: # ✅ Enables manual run from GitHub UI

jobs:
  run-cron:
    runs-on: ubuntu-latest

    steps:
      - name: 📦 Checkout repo
        uses: actions/checkout@v3

      - name: 🧰 Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 📥 Install dependencies
        run: npm install

      - name: 🚀 Run cron script
        run: node scripts/cron-runner.js
