name: Fetch MLB Hot Streaks

on:
  schedule:
    - cron: "0 */6 * * *" # Runs every 6 hours — adjust as needed
  workflow_dispatch: # Allows manual trigger

jobs:
  streaks:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout repo
        uses: actions/checkout@v3

      - name: 🟢 Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 📦 Install dependencies
        run: npm ci

      - name: 🌿 Run fetchHotStreaks script
        env:
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
        run: node scripts/fetchHotStreaks.js
