name: Retrain Models

on:
  schedule:
    - cron: "0 12 * * *" # Daily at 12:00 UTC (4 AM PT)
  workflow_dispatch:

jobs:
  retrain:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Create .env from secrets
        run: |
          echo "SUPABASE_URL=${{ secrets.SUPABASE_URL }}" >> .env
          echo "SUPABASE_SERVICE_ROLE_KEY=${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}" >> .env

      - name: Run retraining script
        run: python backend/scripts/retrain_all_models.py

      - name: Commit updated models
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "auto-trainer"
          git config --global user.email "auto@trainer.bot"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git
          git add models/*.pkl
          git commit -m "🤖 Auto-retrained models" || echo "No changes to commit"
          git push origin main
