name: Retrain Models

on:
  schedule:
    - cron: "0 12 * * *" # Daily at 4 AM UTC
  workflow_dispatch:

jobs:
  retrain:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run retraining script
        run: python backend/scripts/retrain_all_models.py

      - name: Commit updated models
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@users.noreply.github.com"
          git add models/*.pkl
          git commit -m "🤖 Auto-retrained models" || echo "No changes to commit"
          git push origin main
